from __future__ import annotations

from pathlib import Path


APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR.parent
LOCAL_TIMEZONE = "America/New_York"
PROFILE_NOTES_FILE = PROJECT_ROOT / "docs" / "profile_notes.md"
DEFAULT_SHEETS_CREDENTIALS = PROJECT_ROOT / "keys" / "google-credentials.json"
OLLAMA_BASE_URL = "https://ollama.com"
OLLAMA_MODEL = "gemma3:4b-cloud"
OLLAMA_SHORTLIST_SIZE = 15
OLLAMA_MIN_FIT_SCORE = 8
OLLAMA_APPROVED_MAX_PER_RUN = 10
DEFAULT_SHEETS_URL = ""
DEFAULT_SHEETS_TAB = "Jobs"
ARCHIVED_SHEETS_TAB = "Archived Jobs"
JOBSPY_SITES = [
    "linkedin",
    "google",
    "indeed",
]
JOBSPY_HOURS_OLD = 24
JOBSPY_COUNTRY_INDEED = "USA"
# Garima targets a wide company-size range: FAANG-tier down to Series B AI startups
# (Snorkel ~100, Scale ~900, Labelbox ~250). The original list only allowed 1000+
# employee companies, which would have killed every AI/ML startup target.
JOBSPY_BIG_COMPANY_EMPLOYEE_MARKERS = [
    "51 to 200",
    "201 to 500",
    "501 to 1,000",
    "1001 to 5,000",
    "5001 to 10,000",
    "10,000+",
]
JOBSPY_BLOCKED_COMPANY_KEYWORDS = []
# NOTE: Removed "consulting" and "consultancy" from this list. The original
# blocked these to filter staffing-style consultancies, but it would also kill
# Boston Consulting Group, Strategy& Consulting, EY-Parthenon Consulting, etc.
# — all of which are explicit targets. Recruiter/staffing brand names retained.
JOBSPY_BLOCKED_RECRUITER_KEYWORDS = [
    "teksystems",
    "optomi",
    "motion recruitment",
    "robert half",
    "kforce",
    "randstad",
    "modis",
    "insight global",
    "judge group",
    "beacon hill",
    "recruit",
    "staffing",
]
FIT_SCORE_MINIMUM = 4
FIT_DESCRIPTION_POSITIVE_KEYWORDS = [
    "mba",
    "post-mba",
    "post mba",
    "mba new grad",
    "mba pathways",
    "mba full time",
    "mba associate",
    "visa sponsorship",
    "h-1b",
    "h1b",
    "sponsorship available",
    "will sponsor",
    "technical program manager",
    "tpm",
    "program manager",
    "project manager",
    "strategy and operations",
    "strategy & operations",
    "business operations",
    "bizops",
    "chief of staff",
    "engagement manager",
    "implementation manager",
    "delivery manager",
    "transformation",
    "digital transformation",
    "modernization",
    "erp",
    "hcm",
    "workday",
    "servicenow",
    "salesforce",
    "azure",
    "ai",
    "artificial intelligence",
    "machine learning",
    "ml",
    "llm",
    "generative ai",
    "genai",
    "agentic",
    "mlops",
    "enterprise saas",
    "enterprise software",
    "cross-functional",
    "stakeholder",
    "executive",
    "c-suite",
    "director-level",
    "governance",
    "roadmap",
    "kpi",
    "okrs",
    "go-to-market",
    "gtm",
    "pricing strategy",
    "market sizing",
    "financial modeling",
    "roi",
    "business case",
    "change management",
    "process optimization",
    "process automation",
    "workflow automation",
    "consulting",
    "management consulting",
    "strategy consulting",
    "3-5 years",
    "4+ years",
    "5+ years",
    "2-5 years",
    "mid-level",
]
FIT_DESCRIPTION_NEGATIVE_KEYWORDS = [
    "10+ years",
    "12+ years",
    "15+ years",
    "20+ years",
    "minimum of 10 years",
    "minimum of 12 years",
    "must be a us citizen",
    "must be us citizen",
    "us citizens only",
    "us citizen only",
    "citizenship required",
    "no sponsorship",
    "not able to sponsor",
    "unable to sponsor",
    "cannot sponsor",
    "no visa sponsorship",
    "sponsorship not available",
    "security clearance",
    "secret clearance",
    "top secret",
    "ts/sci",
    "public trust",
    "dod clearance",
    "itar",
    "us person",
    "quota",
    "quota-carrying",
    "sales quota",
    "cold calling",
    "ccna",
    "ccnp",
    "datacenter technician",
    "physical infrastructure",
    "network engineering",
    "rack and stack",
    "1099",
    "c2c",
    "corp-to-corp",
    "corp to corp",
    "w2 contract",
    "contract-to-hire",
    "contract to hire",
]
FIT_PREFERRED_LOCATION_KEYWORDS = [
    "san francisco",
    "bay area",
    "south san francisco",
    "palo alto",
    "mountain view",
    "sunnyvale",
    "menlo park",
    "redwood city",
    "san jose",
    "seattle",
    "bellevue",
    "redmond",
    "new york",
    "manhattan",
    "jersey city",
    "boston",
    "cambridge",
    "austin",
    "dallas",
    "chicago",
    "los angeles",
    "washington, dc",
    "arlington",
    "atlanta",
    "pittsburgh",
    "remote",
    "united states",
]
SEARCH_TERMS = [
    "Technical Program Manager",
    "Program Manager",
    "Strategy and Operations",
    "Business Operations Manager",
    "Engagement Manager",
    "Implementation Manager",
    "Senior Consultant",
]
TARGET_LOCATIONS = [
    "San Francisco, California, United States",
    "South San Francisco, California, United States",
    "Palo Alto, California, United States",
    "Mountain View, California, United States",
    "Sunnyvale, California, United States",
    "Menlo Park, California, United States",
    "Redwood City, California, United States",
    "San Jose, California, United States",
    "Los Angeles, California, United States",
    "Seattle, Washington, United States",
    "Bellevue, Washington, United States",
    "Redmond, Washington, United States",
    "New York, New York, United States",
    "Jersey City, New Jersey, United States",
    "Boston, Massachusetts, United States",
    "Cambridge, Massachusetts, United States",
    "Austin, Texas, United States",
    "Dallas, Texas, United States",
    "Chicago, Illinois, United States",
    "Washington, DC, United States",
    "Arlington, Virginia, United States",
    "Atlanta, Georgia, United States",
    "Pittsburgh, Pennsylvania, United States",
    "Remote"
]
MAX_JOBS_PER_DAY = 15
ALLOWED_TITLE_PATTERNS = [
    "technical program manager",
    "technical project manager",
    "program manager",
    "project manager",
    "senior program manager",
    "senior project manager",
    "strategy and operations",
    "strategy & operations",
    "strategy ops",
    "business operations",
    "bizops",
    "chief of staff",
    "engagement manager",
    "senior engagement manager",
    "ai engagement manager",
    "implementation manager",
    "delivery manager",
    "senior consultant",
    "associate consultant",
    "mba associate",
    "mba pathways",
    "operations manager",
    "senior operations manager",
    "product operations",
    "transformation manager",
    "strategic transformation manager",
    "strategic initiatives",
    "customer solutions manager",
    "partner operations manager",
    "gtm strategy",
    "strategy manager",
    "senior strategy",
    "consultant",
    "ai program manager",
    "ml program manager",
    "ai solutions manager",
    "ai engagement",
]
BLOCKED_TITLE_PATTERNS = [
    "senior director",
    "director,",
    "director of",
    "vice president",
    "senior vice president",
    "vp,",
    "vp of",
    "svp",
    "principal",
    "staff",
    "senior staff",
    "distinguished",
    "head of",
    "chief ",
    "cto",
    "ceo",
    "cfo",
    "coo",
    "founder",
    "founding",
    "intern",
    "internship",
    "co-op",
    "summer",
    "new grad engineer",
    "entry level",
    "junior",
    "software engineer",
    "backend engineer",
    "frontend engineer",
    "front-end engineer",
    "full stack",
    "full-stack",
    "mobile engineer",
    "ios engineer",
    "android engineer",
    "devops engineer",
    "sre",
    "site reliability",
    "data engineer",
    "data scientist",
    "machine learning engineer",
    "ml engineer",
    "network engineer",
    "hardware engineer",
    "datacenter technician",
    "field engineer",
    "qa engineer",
    "test engineer",
    "engineering manager",
    "ux designer",
    "ui designer",
    "visual designer",
    "product designer",
    "graphic designer",
    "copywriter",
    "content writer",
    "social media",
    "sales development",
    "sdr",
    "bdr",
    "account executive",
    "inside sales",
    "outside sales",
    "field sales",
    "sales engineer",
    "pre-sales",
    "presales",
    "solutions architect",
    "recruiter",
    "talent acquisition",
    "nurse",
    "clinician",
    "physician",
    "pharmacist",
    "bartender",
    "driver",
    "warehouse",
]
FIT_STRONG_TITLE_PATTERNS = [
    "technical program manager",
    "technical project manager",
    "strategy and operations manager",
    "strategy & operations manager",
    "business operations manager",
    "engagement manager",
    "ai engagement manager",
    "senior engagement manager",
    "implementation manager",
    "chief of staff",
    "mba pathways operations manager",
    "senior consultant",
    "transformation manager",
    "strategic transformation manager",
    "partner operations manager",
    "ai program manager",
    "ml program manager",
]
